# Generated by Django 3.2.4 on 2021-06-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='character',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trails.character'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='character',
            field=models.CharField(choices=[('NE', 'None'), ('ER', 'Engineer'), ('PT', 'Pilot')], default='NE', max_length=2, unique=True),
        ),
    ]
