# Generated by Django 3.2.4 on 2021-06-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.CharField(choices=[('NE', 'None'), ('ER', 'Engineer'), ('PT', 'Pilot')], default='NE', max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ST', 'Stopped'), ('RN', 'Running')], default='ST', max_length=2)),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('clock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='trails.clock')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='trails.game')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NE', 'None'), ('EN', 'Energy'), ('FD', 'Food')], default='NE', max_length=2)),
                ('value', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='trails.game')),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('one_shot', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='trails.game')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('NE', 'None'), ('PA', 'Parameter'), ('CA', 'Character')], default='NE', max_length=2)),
                ('parameter', models.CharField(choices=[('NE', 'None'), ('EN', 'Energy'), ('FD', 'Food')], default='NE', max_length=2)),
                ('value', models.IntegerField(default=0)),
                ('character', models.CharField(choices=[('NE', 'None'), ('ER', 'Engineer'), ('PT', 'Pilot')], default='NE', max_length=2)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='trails.code')),
            ],
        ),
    ]
