# Generated by Django 3.2.5 on 2021-07-19 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_parameter_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trails.code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trails.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='parameter',
            field=models.CharField(choices=[('NE', 'none'), ('EN', 'energy'), ('FD', 'food'), ('HY', 'hygiene'), ('ML', 'moral')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(choices=[('NE', 'none'), ('EN', 'energy'), ('FD', 'food'), ('HY', 'hygiene'), ('ML', 'moral')], default='NE', max_length=2),
        ),
    ]
