# Generated by Django 3.2.4 on 2021-06-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_auto_20210621_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='character',
            new_name='character_class',
        ),
    ]
