# Generated by Django 3.2.5 on 2021-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_alter_parameter_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bearer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
