# Generated by Django 3.2.5 on 2021-07-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_player_bearer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('bearer', 'game')},
        ),
    ]
