# Generated by Django 3.2.5 on 2021-07-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_alter_player_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='action_points',
            field=models.IntegerField(default=0),
        ),
    ]
