# Generated by Django 3.2.5 on 2021-07-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_player_action_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
