# Generated by Django 3.2.5 on 2021-07-23 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0010_auto_20210723_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='code',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='clock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='trails.clock'),
        ),
    ]
