# Generated by Django 3.2.9 on 2021-11-10 13:26

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
  admin = get_user_model().objects.create_superuser("admin", password="Tagungszentrum")
  admin.save()

class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0011_auto_20210723_1151'),
    ]

    operations = [
      migrations.RunPython(create_superuser),
    ]
