# Generated by Django 3.2.5 on 2021-07-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0011_auto_20210723_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trails.player', verbose_name='Player'),
            preserve_default=False,
        ),
    ]
