# Generated by Django 3.2.9 on 2021-12-22 15:42

from django.db import migrations, models


def migrate_clocks_into_games(apps, schema_editor):
    Game = apps.get_model("trails", "Game")

    for game in Game.objects.all():
        if not game.clock:
            continue

        game.clock_speed = game.clock.speed
        game.clock_state = game.clock.state

        game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0013_alter_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='clock_speed',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='game',
            name='clock_state',
            field=models.CharField(
                choices=[('ST', 'Stopped'), ('RN', 'Running')], default='ST', max_length=2),
        ),
        migrations.RunPython(migrate_clocks_into_games),
        migrations.RemoveField(
            model_name='game',
            name='clock',
        ),
        migrations.DeleteModel(
            name='Clock',
        ),
    ]
