# Generated by Django 3.2.9 on 2021-12-24 22:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0014_auto_20211222_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Code', 'verbose_name_plural': 'Codes'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameter'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('NE', '-'), ('PA', 'Parameter'), ('CA', 'Charakter')], default='NE', max_length=2, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='action',
            name='character',
            field=models.CharField(choices=[('NE', '-'), ('ER', 'Ingenieur*in'), ('PT', 'Pilot*in')], default='NE', max_length=2, verbose_name='Character'),
        ),
        migrations.AlterField(
            model_name='action',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='trails.code', verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='action',
            name='parameter',
            field=models.CharField(choices=[('NE', '-'), ('EN', 'Energie'), ('FD', 'Nahrung'), ('HY', 'Hygiene'), ('ML', 'Moral')], default='NE', max_length=2, verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='action',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('NE', '-'), ('ER', 'Ingenieur*in'), ('PT', 'Pilot*in')], default='NE', max_length=2, unique=True, verbose_name='Character Class'),
        ),
        migrations.AlterField(
            model_name='code',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='code',
            name='one_shot',
            field=models.BooleanField(default=False, verbose_name='One-Shot'),
        ),
        migrations.AlterField(
            model_name='code',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='clock_speed',
            field=models.IntegerField(default=1000, verbose_name='Clock Speed'),
        ),
        migrations.AlterField(
            model_name='game',
            name='clock_state',
            field=models.CharField(choices=[('ST', 'Gestoppt'), ('RN', 'Läuft')], default='ST', max_length=2, verbose_name='Clock State'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='log',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trails.code', verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='log',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trails.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='trails.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(choices=[('NE', '-'), ('EN', 'Energie'), ('FD', 'Nahrung'), ('HY', 'Hygiene'), ('ML', 'Moral')], default='NE', max_length=2, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rate',
            field=models.IntegerField(verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='scope',
            field=models.CharField(choices=[('NE', '-'), ('GL', 'Global'), ('FD', 'Benutzer')], default='GL', max_length=2, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.IntegerField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='player',
            name='action_points',
            field=models.IntegerField(default=0, verbose_name='Action Points'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bearer',
            field=models.CharField(max_length=255, verbose_name='Bearer'),
        ),
        migrations.AlterField(
            model_name='player',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.character', verbose_name='Character'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='trails.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
