# Generated by Django 3.2.9 on 2021-12-25 16:23

from django.db import migrations, models
from django.utils.text import slugify
import django.utils.timezone


def add_slug(apps, schema_editor):
    Game = apps.get_model("trails", "Game")

    for game in Game.objects.all():
        game.slug = slugify(game.name)
        game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0016_migrate_enums_20211224_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(add_slug),
    ]
