# Generated by Django 3.2.9 on 2021-12-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0012_alter_code_uuid'),
        ('trails', '0017_add_game_slug'),
    ]

    operations = [
    ]
