# Generated by Django 3.2.9 on 2021-12-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0013_auto_20210724_1304'),
        ('trails', '0018_merge_0012_alter_code_uuid_0017_add_game_slug'),
    ]

    operations = [
    ]
