# Generated by Django 3.2.9 on 2022-01-19 15:52

from django.db import migrations, models
import django.utils.timezone
import uuid


def migrate_clock_speed(apps, schema_editor):
    Game = apps.get_model("trails", "Game")

    for game in Game.objects.all():
        game.clock_speed = game.clock_speed / 1000
        game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0019_merge_20211225_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='clock_duration',
            field=models.IntegerField(
                default=0, verbose_name='Total clock running duration'),
        ),
        migrations.AddField(
            model_name='game',
            name='clock_last_change',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last clock state change'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='uuid',
            field=models.CharField(
                default=uuid.uuid4, max_length=255, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rate',
            field=models.FloatField(verbose_name='Rate'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='max_value',
            field=models.IntegerField(
                default=2147483647, verbose_name='Maximum Value'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='min_value',
            field=models.IntegerField(default=0, verbose_name='Minimum Value'),
        ),
        migrations.AlterField(
            model_name='game',
            name='clock_speed',
            field=models.FloatField(default=1, verbose_name='Clock Speed'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='rate',
            field=models.FloatField(default=0, verbose_name='Rate'),
        ),
        migrations.RunPython(
            code=migrate_clock_speed,
        ),
        migrations.AddField(
            model_name='parameter',
            name='initial_value',
            field=models.IntegerField(default=0, verbose_name='Initial Value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Value'),
        ),
    ]
