# Generated by Django 3.2.9 on 2022-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0020_auto_20220101_1615_squashed_0024_alter_parameter_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='clock_unit',
            field=models.IntegerField(choices=[(1, 'Seconds'), (60, 'Minutes')], default=60, verbose_name='Clock Unit'),
        ),
    ]
