# Generated by Django 3.2.9 on 2022-01-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0021_game_clock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='message',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('none', 'None'), ('parameter', 'Parameter'), ('character', 'Character'), ('message', 'Message')], default='none', max_length=255, verbose_name='Action Type'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='trails.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
