# Generated by Django 4.0.1 on 2022-01-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0022_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trails.character', verbose_name='Character'),
        ),
    ]
