# Generated by Django 4.0.3 on 2022-06-04 18:50

from django.db import migrations, models
import django.db.models.deletion

from ..enums import CharacterType


def migrate_action_characters(apps, schema_editor):
    Character = apps.get_model('trails', 'Character')
    Action = apps.get_model('trails', 'Action')

    for action in Action.objects.all():
        if action.character_class == CharacterType.NONE:
            continue

        action.character, created = Character.objects.get_or_create(
            character_class=action.character_class
        )
        action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0025_alter_player_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(
                max_length=255, unique=True, verbose_name='Character Class'),
        ),
        migrations.RenameField(
            model_name='action',
            old_name='character',
            new_name='character_class'
        ),
        migrations.AddField(
            model_name='action',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='codes', to='trails.character', verbose_name='Character'),
        ),
        migrations.RunPython(migrate_action_characters),
        migrations.RemoveField(
            model_name='action',
            name='character_class'
        )
    ]
