name: Release

on:
  push:
    branches:
      - "+([0-9])?(.{+([0-9]),x}).x"
      - main
      - next
      - next-major
      - beta
      - alpha
  pull_request:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install -g semantic-release@~17.4.4 @semantic-release/git@~9.0.0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
